"""remove email auth columns and tables

Revision ID: c7c4776d50fc
Revises: a3b4c5d6e7f8
Create Date: 2026-07-31 03:10:03.745916
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "c7c4776d50fc"
down_revision: str | None = "a3b4c5d6e7f8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_email_verifications_user_id"), table_name="email_verifications")
    op.drop_table("email_verifications")
    op.drop_index(op.f("ix_password_resets_user_id"), table_name="password_resets")
    op.drop_table("password_resets")
    op.alter_column(
        "users",
        "default_temperature",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column("users", "default_max_tokens", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "users", "default_top_p", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
    )
    op.drop_column("users", "password_hash")
    op.drop_column("users", "is_verified")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("is_verified", sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "users",
        sa.Column("password_hash", sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    )
    op.alter_column(
        "users", "default_top_p", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
    )
    op.alter_column("users", "default_max_tokens", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "users",
        "default_temperature",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.create_table(
        "password_resets",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("token_hash", sa.VARCHAR(length=128), autoincrement=False, nullable=False),
        sa.Column(
            "expires_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("used", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("password_resets_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("password_resets_pkey")),
    )
    op.create_index(
        op.f("ix_password_resets_user_id"), "password_resets", ["user_id"], unique=False
    )
    op.create_table(
        "email_verifications",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("token_hash", sa.VARCHAR(length=128), autoincrement=False, nullable=False),
        sa.Column(
            "expires_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("used", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("email_verifications_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("email_verifications_pkey")),
    )
    op.create_index(
        op.f("ix_email_verifications_user_id"), "email_verifications", ["user_id"], unique=False
    )
    # ### end Alembic commands ###
